name: Sync from Azure DevOps

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
        - uses: yesolutions/mirror-action@master
          with:
            REMOTE: git@devops.iucon-dev.com:22/tfs/DefaultCollection/MANZ%20Website/_git/sync-dummy.git
            GIT_SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            GIT_SSH_NO_VERIFY_HOST: "true"
