name: Sync from Azure DevOps

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: self-hosted

    steps:
      - name: Clone from ADO
        run: |
          rm -rf repo.git
          git clone --mirror "https://${{ secrets.ADO_USERNAME }}:${{ secrets.ADO_PAT }}@devops.iucon-dev.com/tfs/DefaultCollection/MANZ%20Website/_git/sync-dummy" repo.git

      - name: Push to GitHub
        run: |
          cd repo.git
          git push --mirror git@github.com:lina-love/sync-dummy.git
